### ISSUE TITLE
对交易所和货币对的耦合太大了。

### ISSUE THREAD

**Issue by louis-cai** [philsong/Xrypto#3]
如题，如果要添加交易所和货币对，会导致market和broker两个文件夹下面的类爆炸。
我本来是打算在fork中修改的，但看作者最近对文件结构的修改比较大，就先放放吧。

**Comment by philsong** [comment]
这个有好的方法吗？我也在思考中，确实有这个问题，设计不合理。

**Comment by louis-cai** [comment]
可以参考下https://github.com/ericjang/cryptocurrency_arbitrage

**Comment by philsong** [comment]
@louis-cai 这个我看过，还是不太合理，现在初步考虑合并market和broker，然后引入一个brokermanager，负责broker的自动注册，然后只需要引用brokermanager就行了。

**Comment by louis-cai** [comment]
或者可以用工厂模式
